[package]
name = "noql"
version = "0.1.0"
authors = ["Julian Popescu <jpopesculian@gmail.com>"]
edition = "2018"

[features]
default = []

[dependencies]
nl-parser = { path = "../parser" }

[dev-dependencies]
serde_json = "1"
